name: Update Last Modified Date
on:
  push:
    branches: [main]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i "s/Last updated: .*/Last updated: $(date +'%Y-%m-%d')/" docs/index.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/index.md
          git commit -m "Auto-update last modified date"
          git push
